version: '3.8'

networks:
  adonijs:

services:
  build:
    build:
      context: .
      dockerfile: local.dockerfile
    container_name: build
    volumes:
      - ./:/home/node/app
    entrypoint: ['npm', 'install']
    networks:
      - adonijs

  app:
    build:
      context: .
      dockerfile: local.dockerfile
    container_name: skeleton_adonis
    volumes:
      - .:/home/node/app
    ports:
      - '3333:3333'
    networks:
      - adonijs
